[package]
name = "mattermost"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
reqwest.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
